export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	SET_CONTACT: 'SET_CONTACT',
	CLEAR_CONTACT: 'CLEAR_CONTACT',
	LOADING_PHOTO: 'LOADING_PHOTO',
	LOADING_PHOTO_LOAD_MORE: 'LOADING_PHOTO_LOAD_MORE',
	
	GET_PHOTO_BY_QUERY: 'GET_PHOTO_BY_QUERY',
	LOAD_MORE: 'LOAD_MORE',

};
