/* eslint-disable @typescript-eslint/no-explicit-any */
import { PhotoInterface } from '@interfaces';
import { Dispatches } from '@constant';

const DUMMY_DATA = [{
	'id': 'VWcPlbHglYc',
	'slug': 'VWcPlbHglYc',
	'created_at': '2017-06-11T21:17:03Z',
	'updated_at': '2023-06-21T23:45:54Z',
	'promoted_at': '2017-06-12T10:24:27Z',
	'width': 5472,
	'height': 3648,
	'color': '#d9d9d9',
	'blur_hash': 'LTKeG.00Rj%3%ND%oLxuWAaxaeof',
	'description': 'Office',
	'alt_description': 'turned off laptop computer on top of brown wooden table',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1497215728101-856f4ea42174',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/VWcPlbHglYc',
		'html': 'https://unsplash.com/photos/VWcPlbHglYc',
		'download': 'https://unsplash.com/photos/VWcPlbHglYc/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/VWcPlbHglYc/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwxfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 3114,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-04-06T14:20:15Z',
		},
	},
	'user': {
		'id': 'zJgeEcvxc0o',
		'updated_at': '2023-06-21T03:15:31Z',
		'username': 'alesiaskaz',
		'name': 'Alesia Kazantceva',
		'first_name': 'Alesia',
		'last_name': 'Kazantceva',
		'twitter_username': null,
		'portfolio_url': 'http://saltnstreets.com',
		'bio': 'Ottawa-based photographer who loves adventures.\r\n Gear: Canon 6D 85mm, 35 mm;            Leica Q2',
		'location': 'Ottawa',
		'links': {
			'self': 'https://api.unsplash.com/users/alesiaskaz',
			'html': 'https://unsplash.com/@alesiaskaz',
			'photos': 'https://api.unsplash.com/users/alesiaskaz/photos',
			'likes': 'https://api.unsplash.com/users/alesiaskaz/likes',
			'portfolio': 'https://api.unsplash.com/users/alesiaskaz/portfolio',
			'following': 'https://api.unsplash.com/users/alesiaskaz/following',
			'followers': 'https://api.unsplash.com/users/alesiaskaz/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1596578750003-cc29df35976eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1596578750003-cc29df35976eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1596578750003-cc29df35976eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'saltnstreets',
		'total_collections': 9,
		'total_likes': 39,
		'total_photos': 60,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'saltnstreets',
			'portfolio_url': 'http://saltnstreets.com',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'workspace',
		},
		{
			'type': 'landing_page',
			'title': 'background',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'backgrounds',
						'pretty_slug': 'Backgrounds',
					},
				},
				'title': 'Hq background images',
				'subtitle': 'Download free backgrounds',
				'description': 'Browse our beautiful selection of free background images–all submitted by our community of talented contributors and completely free to download and use.',
				'meta_title': 'Best 100+ Free Background Images [HD] | Download your next background photo on Unsplash',
				'meta_description': 'Download the perfect background images. Find over 100+ of the best free background images. Free for commercial use ✓ No attribution required ✓ Copyright-free ✓',
				'cover_photo': {
					'id': 'fMUIVein7Ng',
					'slug': 'fMUIVein7Ng',
					'created_at': '2017-05-15T23:49:10Z',
					'updated_at': '2023-06-18T23:01:28Z',
					'promoted_at': '2017-05-16T09:06:41Z',
					'width': 3847,
					'height': 5583,
					'color': '#c0d9d9',
					'blur_hash': 'LtJ@tjEyjFj[lov~Rja{-Cx]bbWC',
					'description': 'After getting many photos for a project, I am also trying to get images to share with the Unsplash community. Here’s an attempt at abstracting a detail of the amazing architecture of CCPV.',
					'alt_description': 'closeup photo of black and red building',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1494891848038-7bd202a2afeb',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/fMUIVein7Ng',
						'html': 'https://unsplash.com/photos/fMUIVein7Ng',
						'download': 'https://unsplash.com/photos/fMUIVein7Ng/download',
						'download_location': 'https://api.unsplash.com/photos/fMUIVein7Ng/download',
					},
					'likes': 1874,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {
						'architecture-interior': {
							'status': 'approved',
							'approved_on': '2020-04-06T14:20:14Z',
						},
						'wallpapers': {
							'status': 'approved',
							'approved_on': '2020-04-06T14:20:09Z',
						},
						'color-of-water': {
							'status': 'approved',
							'approved_on': '2022-04-21T15:04:21Z',
						},
					},
					'premium': false,
					'plus': false,
					'user': {
						'id': 'hnq0aaqF_Qo',
						'updated_at': '2023-06-15T17:34:10Z',
						'username': 'scottwebb',
						'name': 'Scott Webb',
						'first_name': 'Scott',
						'last_name': 'Webb',
						'twitter_username': null,
						'portfolio_url': 'https://scottwebb.me/',
						'bio': 'If you like my work and you\'d like to support me, you can consider a donation 👉  http://www.paypal.me/scottrwebb | Donation goal for a new lens: $351.01 of $449 | Thank you Jay D. 🙏',
						'location': 'London, Ontario, Canada',
						'links': {
							'self': 'https://api.unsplash.com/users/scottwebb',
							'html': 'https://unsplash.com/@scottwebb',
							'photos': 'https://api.unsplash.com/users/scottwebb/photos',
							'likes': 'https://api.unsplash.com/users/scottwebb/likes',
							'portfolio': 'https://api.unsplash.com/users/scottwebb/portfolio',
							'following': 'https://api.unsplash.com/users/scottwebb/following',
							'followers': 'https://api.unsplash.com/users/scottwebb/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-1598557047185-d94f7fc56f69image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-1598557047185-d94f7fc56f69image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-1598557047185-d94f7fc56f69image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'scottwebb',
						'total_collections': 46,
						'total_likes': 4152,
						'total_photos': 804,
						'accepted_tos': true,
						'for_hire': true,
						'social': {
							'instagram_username': 'scottwebb',
							'portfolio_url': 'https://scottwebb.me/',
							'twitter_username': null,
							'paypal_email': null,
						},
					},
				},
			},
		},
	],
},
{
	'id': 'eHD8Y1Znfpk',
	'slug': 'eHD8Y1Znfpk',
	'created_at': '2017-06-13T15:14:07Z',
	'updated_at': '2023-06-22T03:01:35Z',
	'promoted_at': null,
	'width': 2301,
	'height': 1536,
	'color': '#404040',
	'blur_hash': 'LQDl~9_NS%fkV?s-t7t74.M{xtxu',
	'description': 'Spacious boardroom',
	'alt_description': 'photo of dining table and chairs inside room',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1497366811353-6870744d04b2',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/eHD8Y1Znfpk',
		'html': 'https://unsplash.com/photos/eHD8Y1Znfpk',
		'download': 'https://unsplash.com/photos/eHD8Y1Znfpk/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/eHD8Y1Znfpk/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwyfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 2498,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'current-events': {
			'status': 'approved',
			'approved_on': '2020-04-21T20:37:06Z',
		},
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-04-29T09:32:31Z',
		},
		'interiors': {
			'status': 'approved',
			'approved_on': '2020-11-20T13:58:51Z',
		},
	},
	'user': {
		'id': '8JndoHx8RCw',
		'updated_at': '2023-05-10T22:49:01Z',
		'username': 'sunday_digital',
		'name': 'Nastuh Abootalebi',
		'first_name': 'Nastuh',
		'last_name': 'Abootalebi',
		'twitter_username': null,
		'portfolio_url': 'http://sunday.digital',
		'bio': null,
		'location': 'Munich',
		'links': {
			'self': 'https://api.unsplash.com/users/sunday_digital',
			'html': 'https://unsplash.com/@sunday_digital',
			'photos': 'https://api.unsplash.com/users/sunday_digital/photos',
			'likes': 'https://api.unsplash.com/users/sunday_digital/likes',
			'portfolio': 'https://api.unsplash.com/users/sunday_digital/portfolio',
			'following': 'https://api.unsplash.com/users/sunday_digital/following',
			'followers': 'https://api.unsplash.com/users/sunday_digital/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1553072872488-7bc864ac59f0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1553072872488-7bc864ac59f0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1553072872488-7bc864ac59f0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'prsn.kitty',
		'total_collections': 1,
		'total_likes': 1,
		'total_photos': 12,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'prsn.kitty',
			'portfolio_url': 'http://sunday.digital',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'interior',
		},
		{
			'type': 'search',
			'title': 'room',
		},
		{
			'type': 'search',
			'title': 'workplace',
		},
	],
},
{
	'id': 'DyFjxmHt3Es',
	'slug': 'DyFjxmHt3Es',
	'created_at': '2020-01-20T02:41:05Z',
	'updated_at': '2023-06-22T08:11:29Z',
	'promoted_at': null,
	'width': 4912,
	'height': 7360,
	'color': '#c0c0c0',
	'blur_hash': 'LKHxc]bvn#R*Z}s,M{t7~pV@M{t7',
	'description': null,
	'alt_description': 'black and brown chairs and tables',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1579487785973-74d2ca7abdd5',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/DyFjxmHt3Es',
		'html': 'https://unsplash.com/photos/DyFjxmHt3Es',
		'download': 'https://unsplash.com/photos/DyFjxmHt3Es/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/DyFjxmHt3Es/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHwzfHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 354,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-06-18T14:25:08Z',
		},
	},
	'user': {
		'id': '0CsT0Oztn6Q',
		'updated_at': '2023-06-15T17:05:16Z',
		'username': 'joselosada',
		'name': 'Jose Losada',
		'first_name': 'Jose',
		'last_name': 'Losada',
		'twitter_username': null,
		'portfolio_url': null,
		'bio': 'Graphic Designer + Producer + Singer + Photographer.\r\nYou can contact me at joselosada88@icloud.com. Houston based!  https://www.patreon.com/joselosada',
		'location': 'Houston, TX',
		'links': {
			'self': 'https://api.unsplash.com/users/joselosada',
			'html': 'https://unsplash.com/@joselosada',
			'photos': 'https://api.unsplash.com/users/joselosada/photos',
			'likes': 'https://api.unsplash.com/users/joselosada/likes',
			'portfolio': 'https://api.unsplash.com/users/joselosada/portfolio',
			'following': 'https://api.unsplash.com/users/joselosada/following',
			'followers': 'https://api.unsplash.com/users/joselosada/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1575348346879-1ef45aa3cd47image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1575348346879-1ef45aa3cd47image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1575348346879-1ef45aa3cd47image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'joselosadaphotography',
		'total_collections': 0,
		'total_likes': 2,
		'total_photos': 211,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'joselosadaphotography',
			'portfolio_url': null,
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'cubicle',
		},
		{
			'type': 'landing_page',
			'title': 'green',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'wallpapers',
						'pretty_slug': 'HD Wallpapers',
					},
					'category': {
						'slug': 'colors',
						'pretty_slug': 'Color',
					},
					'subcategory': {
						'slug': 'green',
						'pretty_slug': 'Green',
					},
				},
				'title': 'Hd green wallpapers',
				'subtitle': 'Download free green wallpapers',
				'description': 'Choose from a curated selection of green wallpapers for your mobile and desktop screens. Always free on Unsplash.',
				'meta_title': 'Green Wallpapers: Free HD Download [500+ HQ] | Unsplash',
				'meta_description': 'Choose from hundreds of free green wallpapers. Download HD wallpapers for free on Unsplash.',
				'cover_photo': {
					'id': 'OOE4xAnBhKo',
					'slug': 'OOE4xAnBhKo',
					'created_at': '2017-06-12T06:59:41Z',
					'updated_at': '2023-06-14T14:01:37Z',
					'promoted_at': '2017-06-12T10:38:54Z',
					'width': 3000,
					'height': 4498,
					'color': '#0c260c',
					'blur_hash': 'L20n+6ZTUikUclbGkUeqVcknkna4',
					'description': 'Infinite Ferns',
					'alt_description': 'photo of green fern plant',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1497250681960-ef046c08a56e',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/OOE4xAnBhKo',
						'html': 'https://unsplash.com/photos/OOE4xAnBhKo',
						'download': 'https://unsplash.com/photos/OOE4xAnBhKo/download',
						'download_location': 'https://api.unsplash.com/photos/OOE4xAnBhKo/download',
					},
					'likes': 5725,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {
						'wallpapers': {
							'status': 'approved',
							'approved_on': '2020-04-06T14:20:10Z',
						},
						'nature': {
							'status': 'approved',
							'approved_on': '2020-04-06T14:20:12Z',
						},
					},
					'premium': false,
					'plus': false,
					'user': {
						'id': 'kPVbz0Q7VmM',
						'updated_at': '2023-06-06T17:33:34Z',
						'username': 'xteemu',
						'name': 'Teemu Paananen',
						'first_name': 'Teemu',
						'last_name': 'Paananen',
						'twitter_username': 'spacekablooie',
						'portfolio_url': 'http://instagram.com/teemujp',
						'bio': 'Designer and photographer. Main camera Sony A7Rii.',
						'location': 'Stockholm, Sweden',
						'links': {
							'self': 'https://api.unsplash.com/users/xteemu',
							'html': 'https://unsplash.com/@xteemu',
							'photos': 'https://api.unsplash.com/users/xteemu/photos',
							'likes': 'https://api.unsplash.com/users/xteemu/likes',
							'portfolio': 'https://api.unsplash.com/users/xteemu/portfolio',
							'following': 'https://api.unsplash.com/users/xteemu/following',
							'followers': 'https://api.unsplash.com/users/xteemu/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-1539627965411-de9ffec94df4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-1539627965411-de9ffec94df4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-1539627965411-de9ffec94df4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'teemujp',
						'total_collections': 2,
						'total_likes': 94,
						'total_photos': 7,
						'accepted_tos': true,
						'for_hire': false,
						'social': {
							'instagram_username': 'teemujp',
							'portfolio_url': 'http://instagram.com/teemujp',
							'twitter_username': 'spacekablooie',
							'paypal_email': null,
						},
					},
				},
			},
		},
	],
},
{
	'id': '5U_28ojjgms',
	'slug': '5U_28ojjgms',
	'created_at': '2019-09-20T15:40:25Z',
	'updated_at': '2023-06-21T23:49:44Z',
	'promoted_at': '2019-09-22T08:01:59Z',
	'width': 4821,
	'height': 2712,
	'color': '#262626',
	'blur_hash': 'LSF=m#~qE1Z~_3-;xFV@E1RjofR*',
	'description': 'Collaborative Meeting',
	'alt_description': 'people sitting on chair',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1568992687947-868a62a9f521',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/5U_28ojjgms',
		'html': 'https://unsplash.com/photos/5U_28ojjgms',
		'download': 'https://unsplash.com/photos/5U_28ojjgms/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/5U_28ojjgms/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw0fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 1138,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2021-08-23T15:13:05Z',
		},
	},
	'user': {
		'id': 'Q9Ig7Srx2OI',
		'updated_at': '2023-06-09T06:05:55Z',
		'username': 'raddfilms',
		'name': 'Redd F',
		'first_name': 'Redd',
		'last_name': 'F',
		'twitter_username': null,
		'portfolio_url': 'https://www.raddfilms.com/',
		'bio': 'Photographer & Filmmaker\r\n',
		'location': 'Edmonton, Alberta',
		'links': {
			'self': 'https://api.unsplash.com/users/raddfilms',
			'html': 'https://unsplash.com/@raddfilms',
			'photos': 'https://api.unsplash.com/users/raddfilms/photos',
			'likes': 'https://api.unsplash.com/users/raddfilms/likes',
			'portfolio': 'https://api.unsplash.com/users/raddfilms/portfolio',
			'following': 'https://api.unsplash.com/users/raddfilms/following',
			'followers': 'https://api.unsplash.com/users/raddfilms/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1651635111298-b88086877026image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1651635111298-b88086877026image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1651635111298-b88086877026image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'radd.films',
		'total_collections': 0,
		'total_likes': 244,
		'total_photos': 614,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'radd.films',
			'portfolio_url': 'https://www.raddfilms.com/',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'business',
		},
		{
			'type': 'landing_page',
			'title': 'people',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'images',
						'pretty_slug': 'Images',
					},
					'category': {
						'slug': 'people',
						'pretty_slug': 'People',
					},
				},
				'title': 'People images & pictures',
				'subtitle': 'Download free people images',
				'description': 'Human faces speak to us in a way that language cannot. Everyone recognize a smile, a frown, tears. Unsplash has the finest selection of people images on the web: high-def and curated for quality. Family, friends, men, women, Unsplash has photos for all.',
				'meta_title': 'People Pictures [HQ] | Download Free Images on Unsplash',
				'meta_description': 'Choose from hundreds of free people pictures. Download HD people photos for free on Unsplash.',
				'cover_photo': {
					'id': 'PmNjS6b3XP4',
					'slug': 'PmNjS6b3XP4',
					'created_at': '2017-04-20T22:04:07Z',
					'updated_at': '2023-06-14T07:01:23Z',
					'promoted_at': '2017-04-21T16:00:49Z',
					'width': 4630,
					'height': 3087,
					'color': '#a6d9d9',
					'blur_hash': 'LjI=x%:QUbv#NHWVa}kCt7jFjZfQ',
					'description': 'Summer in France with baby',
					'alt_description': 'woman carrying baby while walking',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1492725764893-90b379c2b6e7',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/PmNjS6b3XP4',
						'html': 'https://unsplash.com/photos/PmNjS6b3XP4',
						'download': 'https://unsplash.com/photos/PmNjS6b3XP4/download',
						'download_location': 'https://api.unsplash.com/photos/PmNjS6b3XP4/download',
					},
					'likes': 2703,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {
						'current-events': {
							'status': 'approved',
							'approved_on': '2021-03-01T12:52:57Z',
						},
					},
					'premium': false,
					'plus': false,
					'user': {
						'id': '7S_pCRiCiQo',
						'updated_at': '2023-06-09T08:04:35Z',
						'username': 'thedakotacorbin',
						'name': 'Dakota Corbin',
						'first_name': 'Dakota',
						'last_name': 'Corbin',
						'twitter_username': 'thedakotacorbin',
						'portfolio_url': null,
						'bio': 'Husband | Father | Creator',
						'location': 'Utah, United States',
						'links': {
							'self': 'https://api.unsplash.com/users/thedakotacorbin',
							'html': 'https://unsplash.com/@thedakotacorbin',
							'photos': 'https://api.unsplash.com/users/thedakotacorbin/photos',
							'likes': 'https://api.unsplash.com/users/thedakotacorbin/likes',
							'portfolio': 'https://api.unsplash.com/users/thedakotacorbin/portfolio',
							'following': 'https://api.unsplash.com/users/thedakotacorbin/following',
							'followers': 'https://api.unsplash.com/users/thedakotacorbin/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-1623795199834-f8109281554dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-1623795199834-f8109281554dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-1623795199834-f8109281554dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'thedakotacorbin',
						'total_collections': 0,
						'total_likes': 1,
						'total_photos': 44,
						'accepted_tos': true,
						'for_hire': true,
						'social': {
							'instagram_username': 'thedakotacorbin',
							'portfolio_url': null,
							'twitter_username': 'thedakotacorbin',
							'paypal_email': null,
						},
					},
				},
			},
		},
	],
},
{
	'id': 'BlIhVfXbi9s',
	'slug': 'BlIhVfXbi9s',
	'created_at': '2018-08-01T02:23:46Z',
	'updated_at': '2023-06-22T06:05:14Z',
	'promoted_at': '2021-06-19T15:50:28Z',
	'width': 6016,
	'height': 4016,
	'color': '#c0c0c0',
	'blur_hash': 'LCMaO.4m-=D%%NWUWBt8xvWBM_of',
	'description': 'My Bedroom-Simplicity',
	'alt_description': 'white desk lamp beside green plant',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1533090161767-e6ffed986c88',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/BlIhVfXbi9s',
		'html': 'https://unsplash.com/photos/BlIhVfXbi9s',
		'download': 'https://unsplash.com/photos/BlIhVfXbi9s/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/BlIhVfXbi9s/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw1fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 7864,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'wallpapers': {
			'status': 'approved',
			'approved_on': '2021-08-16T09:16:02Z',
		},
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-04-06T14:20:15Z',
		},
		'interiors': {
			'status': 'approved',
			'approved_on': '2021-07-08T10:28:18Z',
		},
	},
	'user': {
		'id': 'X_Q46R0vWhc',
		'updated_at': '2023-06-15T14:23:43Z',
		'username': 'srosinger3997',
		'name': 'Samantha Gades',
		'first_name': 'Samantha',
		'last_name': 'Gades',
		'twitter_username': null,
		'portfolio_url': 'https://www.gadesphotography.co',
		'bio': '-- MPLS Wedding Photographer -- ',
		'location': 'Minneapolis, Mn',
		'links': {
			'self': 'https://api.unsplash.com/users/srosinger3997',
			'html': 'https://unsplash.com/@srosinger3997',
			'photos': 'https://api.unsplash.com/users/srosinger3997/photos',
			'likes': 'https://api.unsplash.com/users/srosinger3997/likes',
			'portfolio': 'https://api.unsplash.com/users/srosinger3997/portfolio',
			'following': 'https://api.unsplash.com/users/srosinger3997/following',
			'followers': 'https://api.unsplash.com/users/srosinger3997/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1529637327654-f0da5df23812?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1529637327654-f0da5df23812?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1529637327654-f0da5df23812?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'samanthagades',
		'total_collections': 0,
		'total_likes': 9,
		'total_photos': 210,
		'accepted_tos': true,
		'for_hire': false,
		'social': {
			'instagram_username': 'samanthagades',
			'portfolio_url': 'https://www.gadesphotography.co',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'landing_page',
			'title': 'website',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'backgrounds',
						'pretty_slug': 'Backgrounds',
					},
					'category': {
						'slug': 'apps',
						'pretty_slug': 'App',
					},
					'subcategory': {
						'slug': 'website',
						'pretty_slug': 'Website',
					},
				},
				'title': 'Website backgrounds',
				'subtitle': 'Download free website background images',
				'description': 'Looking for some beautiful images for your website? Unsplash has you covered. Find the perfect website background from our massive collection of professional-quality images. Each is free to use!',
				'meta_title': '900+ Website Background Images: Download HD Backgrounds on Unsplash',
				'meta_description': 'Choose from hundreds of free website backgrounds. Download beautiful, curated free backgrounds on Unsplash.',
				'cover_photo': {
					'id': '-zr2ZUMvChY',
					'slug': '-zr2ZUMvChY',
					'created_at': '2020-03-20T04:14:20Z',
					'updated_at': '2023-06-17T01:11:27Z',
					'promoted_at': '2020-03-21T14:21:04Z',
					'width': 3362,
					'height': 4202,
					'color': '#c0a68c',
					'blur_hash': 'LAHBYn00Dh9bMyRP4;s,Ql%1?coJ',
					'description': null,
					'alt_description': 'man in white crew neck t-shirt and black sunglasses standing on brown brick floor during',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1584677626646-7c8f83690304?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1584677626646-7c8f83690304?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1584677626646-7c8f83690304?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1584677626646-7c8f83690304?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1584677626646-7c8f83690304?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1584677626646-7c8f83690304',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/-zr2ZUMvChY',
						'html': 'https://unsplash.com/photos/-zr2ZUMvChY',
						'download': 'https://unsplash.com/photos/-zr2ZUMvChY/download',
						'download_location': 'https://api.unsplash.com/photos/-zr2ZUMvChY/download',
					},
					'likes': 26,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {},
					'premium': false,
					'plus': false,
					'user': {
						'id': 'ba4iqw-n3No',
						'updated_at': '2023-06-09T06:32:24Z',
						'username': 'marcussantosr',
						'name': 'Marcus Santos',
						'first_name': 'Marcus',
						'last_name': 'Santos',
						'twitter_username': null,
						'portfolio_url': 'http://marcussantosr.com',
						'bio': 'Hiperativo, Publicitario e amante da fotometria\r\n Instagram:@marcussantosr',
						'location': null,
						'links': {
							'self': 'https://api.unsplash.com/users/marcussantosr',
							'html': 'https://unsplash.com/@marcussantosr',
							'photos': 'https://api.unsplash.com/users/marcussantosr/photos',
							'likes': 'https://api.unsplash.com/users/marcussantosr/likes',
							'portfolio': 'https://api.unsplash.com/users/marcussantosr/portfolio',
							'following': 'https://api.unsplash.com/users/marcussantosr/following',
							'followers': 'https://api.unsplash.com/users/marcussantosr/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-fb-1545319920-8c2311af02a0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-fb-1545319920-8c2311af02a0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-fb-1545319920-8c2311af02a0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'marcussantosr',
						'total_collections': 2,
						'total_likes': 3,
						'total_photos': 160,
						'accepted_tos': true,
						'for_hire': true,
						'social': {
							'instagram_username': 'marcussantosr',
							'portfolio_url': 'http://marcussantosr.com',
							'twitter_username': null,
							'paypal_email': null,
						},
					},
				},
			},
		},
		{
			'type': 'search',
			'title': 'clean',
		},
		{
			'type': 'search',
			'title': 'blog',
		},
	],
},
{
	'id': 'FV3GConVSss',
	'slug': 'FV3GConVSss',
	'created_at': '2018-04-26T16:07:35Z',
	'updated_at': '2023-06-21T23:53:43Z',
	'promoted_at': '2018-04-27T12:24:09Z',
	'width': 3762,
	'height': 2508,
	'color': '#d9d9d9',
	'blur_hash': 'LFLqe8QlM|x]~W4TtSVrpd.9DiW;',
	'description': 'workspace',
	'alt_description': 'black floor lamp on living room sofa',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1524758631624-e2822e304c36',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/FV3GConVSss',
		'html': 'https://unsplash.com/photos/FV3GConVSss',
		'download': 'https://unsplash.com/photos/FV3GConVSss/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/FV3GConVSss/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw2fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 4277,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'architecture-interior': {
			'status': 'approved',
			'approved_on': '2021-09-24T10:49:44Z',
		},
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-04-06T14:20:15Z',
		},
		'interiors': {
			'status': 'approved',
			'approved_on': '2020-06-03T13:49:17Z',
		},
	},
	'user': {
		'id': 'zYw2OJ152h8',
		'updated_at': '2023-06-22T08:22:02Z',
		'username': 'heftiba',
		'name': 'Toa Heftiba',
		'first_name': 'Toa',
		'last_name': 'Heftiba',
		'twitter_username': 'toaheftiba',
		'portfolio_url': 'http://heftiba.co.uk/',
		'bio': 'ᴘʀᴏᴅᴜᴄᴛ | ꜰᴏᴏᴅ | ʟɪꜰᴇꜱᴛʏʟᴇ ᴘʜᴏᴛᴏɢʀᴀᴘʜᴇʀ • ᴀ ꜰᴀɴ ᴏꜰ ᴏᴅᴅ ᴛʜɪɴɢꜱ ᴀɴᴅ ɢᴏᴏᴅ ʜᴜᴍᴏᴜʀ. 🙂\r\n👉🏻ᴄʟɪᴄᴋ ᴛʜᴇ \'ᴄᴏʟʟᴇᴄᴛɪᴏɴꜱ\' ᴛᴀʙ ʙᴇʟᴏᴡ ᴛᴏ ᴠɪᴇᴡ ᴍʏ ɪᴍᴀɢᴇꜱ ɪɴ ᴏʀɢᴀɴɪꜱᴇᴅ ꜰᴏʟᴅᴇʀꜱ.  ᴡʜʏ ɴᴏᴛ ꜱᴀʏ ʜᴇʟʟᴏ ⚡️ ɪɢ: @ʜᴇꜰᴛɪʙᴀ.ᴄᴏ.ᴜᴋ ',
		'location': 'UK',
		'links': {
			'self': 'https://api.unsplash.com/users/heftiba',
			'html': 'https://unsplash.com/@heftiba',
			'photos': 'https://api.unsplash.com/users/heftiba/photos',
			'likes': 'https://api.unsplash.com/users/heftiba/likes',
			'portfolio': 'https://api.unsplash.com/users/heftiba/portfolio',
			'following': 'https://api.unsplash.com/users/heftiba/following',
			'followers': 'https://api.unsplash.com/users/heftiba/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1605780274397-200ea3604d6fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1605780274397-200ea3604d6fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1605780274397-200ea3604d6fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'heftiba.co.uk',
		'total_collections': 41,
		'total_likes': 2433,
		'total_photos': 3528,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'heftiba.co.uk',
			'portfolio_url': 'http://heftiba.co.uk/',
			'twitter_username': 'toaheftiba',
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'interior',
		},
		{
			'type': 'search',
			'title': 'furniture',
		},
	],
},
{
	'id': 'gMsnXqILjp4',
	'slug': 'gMsnXqILjp4',
	'created_at': '2018-11-20T20:03:07Z',
	'updated_at': '2023-06-21T23:46:29Z',
	'promoted_at': null,
	'width': 6000,
	'height': 4000,
	'color': '#f3f3f3',
	'blur_hash': 'LWIg_#R*0KM{_NjuIAjYJ8WBIVR*',
	'description': null,
	'alt_description': 'man standing in front of people sitting beside table with laptop computers',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1542744173-8e7e53415bb0',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/gMsnXqILjp4',
		'html': 'https://unsplash.com/photos/gMsnXqILjp4',
		'download': 'https://unsplash.com/photos/gMsnXqILjp4/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/gMsnXqILjp4/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw3fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 2229,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2021-05-20T09:03:39Z',
		},
	},
	'user': {
		'id': 'pKjvs-fyRp4',
		'updated_at': '2023-06-09T07:23:02Z',
		'username': 'campaign_creators',
		'name': 'Campaign Creators',
		'first_name': 'Campaign',
		'last_name': 'Creators',
		'twitter_username': null,
		'portfolio_url': 'https://www.campaigncreators.com/',
		'bio': 'Our goal is to provide Business/Marketing specific pictures for any blogger to use, for free! It really helps us out if you backlink us when using our photos https://www.campaigncreators.com/ ',
		'location': null,
		'links': {
			'self': 'https://api.unsplash.com/users/campaign_creators',
			'html': 'https://unsplash.com/@campaign_creators',
			'photos': 'https://api.unsplash.com/users/campaign_creators/photos',
			'likes': 'https://api.unsplash.com/users/campaign_creators/likes',
			'portfolio': 'https://api.unsplash.com/users/campaign_creators/portfolio',
			'following': 'https://api.unsplash.com/users/campaign_creators/following',
			'followers': 'https://api.unsplash.com/users/campaign_creators/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1533247474726-9e414fff2b4f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1533247474726-9e414fff2b4f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1533247474726-9e414fff2b4f?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': null,
		'total_collections': 0,
		'total_likes': 0,
		'total_photos': 54,
		'accepted_tos': true,
		'for_hire': false,
		'social': {
			'instagram_username': null,
			'portfolio_url': 'https://www.campaigncreators.com/',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'work',
		},
		{
			'type': 'search',
			'title': 'presentation',
		},
	],
},
{
	'id': 'dIMJWLx1YbE',
	'slug': 'dIMJWLx1YbE',
	'created_at': '2018-09-03T07:02:42Z',
	'updated_at': '2023-06-22T00:04:06Z',
	'promoted_at': '2018-09-04T16:06:10Z',
	'width': 3605,
	'height': 4806,
	'color': '#262626',
	'blur_hash': 'LPEyoM9Ft8R%_NRit7kCNsM{ozt7',
	'description': null,
	'alt_description': 'MacBook Pro',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1535957998253-26ae1ef29506?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1535957998253-26ae1ef29506?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1535957998253-26ae1ef29506?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1535957998253-26ae1ef29506?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1535957998253-26ae1ef29506?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1535957998253-26ae1ef29506',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/dIMJWLx1YbE',
		'html': 'https://unsplash.com/photos/dIMJWLx1YbE',
		'download': 'https://unsplash.com/photos/dIMJWLx1YbE/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/dIMJWLx1YbE/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw4fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 2244,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2020-04-06T14:20:15Z',
		},
	},
	'user': {
		'id': 'wtg3a4xlj2w',
		'updated_at': '2023-06-14T05:01:36Z',
		'username': 'olenkasergienko',
		'name': 'Olena Sergienko',
		'first_name': 'Olena',
		'last_name': 'Sergienko',
		'twitter_username': null,
		'portfolio_url': 'https://www.behance.net/olenkasergienko',
		'bio': '🇺🇦 From Kyiv with love 📸🖖\r\n🇵🇱 Currently in Warsaw DM me for brand content | thanks for the PayPal donation',
		'location': 'Warszawa',
		'links': {
			'self': 'https://api.unsplash.com/users/olenkasergienko',
			'html': 'https://unsplash.com/@olenkasergienko',
			'photos': 'https://api.unsplash.com/users/olenkasergienko/photos',
			'likes': 'https://api.unsplash.com/users/olenkasergienko/likes',
			'portfolio': 'https://api.unsplash.com/users/olenkasergienko/portfolio',
			'following': 'https://api.unsplash.com/users/olenkasergienko/following',
			'followers': 'https://api.unsplash.com/users/olenkasergienko/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-1630491198015-3d997fe8db72image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-1630491198015-3d997fe8db72image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-1630491198015-3d997fe8db72image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': 'olenka_sergienko',
		'total_collections': 1,
		'total_likes': 238,
		'total_photos': 809,
		'accepted_tos': true,
		'for_hire': true,
		'social': {
			'instagram_username': 'olenka_sergienko',
			'portfolio_url': 'https://www.behance.net/olenkasergienko',
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'search',
			'title': 'workspace',
		},
		{
			'type': 'landing_page',
			'title': 'computer',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'wallpapers',
						'pretty_slug': 'HD Wallpapers',
					},
					'category': {
						'slug': 'desktop',
						'pretty_slug': 'Desktop',
					},
					'subcategory': {
						'slug': 'computer',
						'pretty_slug': 'Computer',
					},
				},
				'title': 'Hd computer wallpapers',
				'subtitle': 'Download free computer wallpapers',
				'description': 'Choose from a curated selection of computer wallpapers for your mobile and desktop screens. Always free on Unsplash.',
				'meta_title': 'Computer Wallpapers: Free HD Download [500+ HQ] | Unsplash',
				'meta_description': 'Choose from hundreds of free computer wallpapers. Download HD wallpapers for free on Unsplash.',
				'cover_photo': {
					'id': 'wyEinDRV88I',
					'slug': 'wyEinDRV88I',
					'created_at': '2016-11-18T21:01:40Z',
					'updated_at': '2023-06-18T14:01:23Z',
					'promoted_at': '2016-11-18T21:01:40Z',
					'width': 7952,
					'height': 5304,
					'color': '#c0c0c0',
					'blur_hash': 'LhF$CS?bRjRj~p%LV@WCSiWWWBof',
					'description': null,
					'alt_description': 'woman taking photo of buildings',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1479502806991-251c94be6b15?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1479502806991-251c94be6b15',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/wyEinDRV88I',
						'html': 'https://unsplash.com/photos/wyEinDRV88I',
						'download': 'https://unsplash.com/photos/wyEinDRV88I/download',
						'download_location': 'https://api.unsplash.com/photos/wyEinDRV88I/download',
					},
					'likes': 581,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {
						'wallpapers': {
							'status': 'approved',
							'approved_on': '2020-04-06T14:20:09Z',
						},
					},
					'premium': false,
					'plus': false,
					'user': {
						'id': 'WylEZk6e2xA',
						'updated_at': '2023-06-13T19:02:24Z',
						'username': 'thoughtcatalog',
						'name': 'Thought Catalog',
						'first_name': 'Thought',
						'last_name': 'Catalog',
						'twitter_username': 'thoughtcatalog',
						'portfolio_url': 'http://thoughtcatalog.com/?utm_campaign=platform-link&utm_source=unsplash&utm_medium=profile',
						'bio': 'We\'re a digital magazine based in Brooklyn. We use Unsplash to share with the world some of our best in-house photography.',
						'location': 'New York',
						'links': {
							'self': 'https://api.unsplash.com/users/thoughtcatalog',
							'html': 'https://unsplash.com/@thoughtcatalog',
							'photos': 'https://api.unsplash.com/users/thoughtcatalog/photos',
							'likes': 'https://api.unsplash.com/users/thoughtcatalog/likes',
							'portfolio': 'https://api.unsplash.com/users/thoughtcatalog/portfolio',
							'following': 'https://api.unsplash.com/users/thoughtcatalog/following',
							'followers': 'https://api.unsplash.com/users/thoughtcatalog/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-1479502385647-8aa0d0e9a87b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-1479502385647-8aa0d0e9a87b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-1479502385647-8aa0d0e9a87b?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'thoughtcatalog',
						'total_collections': 5,
						'total_likes': 12,
						'total_photos': 173,
						'accepted_tos': true,
						'for_hire': true,
						'social': {
							'instagram_username': 'thoughtcatalog',
							'portfolio_url': 'http://thoughtcatalog.com/?utm_campaign=platform-link&utm_source=unsplash&utm_medium=profile',
							'twitter_username': 'thoughtcatalog',
							'paypal_email': null,
						},
					},
				},
			},
		},
	],
},
{
	'id': 'YI_9SivVt_s',
	'slug': 'YI_9SivVt_s',
	'created_at': '2020-12-01T21:21:33Z',
	'updated_at': '2023-06-21T23:47:52Z',
	'promoted_at': null,
	'width': 5842,
	'height': 3895,
	'color': '#d9c0c0',
	'blur_hash': 'LXIO92-;9ZW;~VxaM{RjMxj?t6t6',
	'description': null,
	'alt_description': 'people sitting on chair in front of computer',
	'urls': {
		'raw': 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3',
		'full': 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?crop=entropy&cs=srgb&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=85',
		'regular': 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=1080',
		'small': 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=400',
		'thumb': 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA&ixlib=rb-4.0.3&q=80&w=200',
		'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1606857521015-7f9fcf423740',
	},
	'links': {
		'self': 'https://api.unsplash.com/photos/YI_9SivVt_s',
		'html': 'https://unsplash.com/photos/YI_9SivVt_s',
		'download': 'https://unsplash.com/photos/YI_9SivVt_s/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
		'download_location': 'https://api.unsplash.com/photos/YI_9SivVt_s/download?ixid=M3w0NjUwNjl8MHwxfHNlYXJjaHw5fHxvZmZpY2V8ZW58MHx8fHwxNjg3NDIyMzkyfDA',
	},
	'likes': 532,
	'liked_by_user': false,
	'current_user_collections': [],
	'sponsorship': null,
	'topic_submissions': {
		'business-work': {
			'status': 'approved',
			'approved_on': '2021-08-27T14:16:10Z',
		},
	},
	'user': {
		'id': '913JlvqZHgo',
		'updated_at': '2023-04-23T22:16:21Z',
		'username': 'israelandrxde',
		'name': 'Israel Andrade',
		'first_name': 'Israel',
		'last_name': 'Andrade',
		'twitter_username': null,
		'portfolio_url': null,
		'bio': null,
		'location': null,
		'links': {
			'self': 'https://api.unsplash.com/users/israelandrxde',
			'html': 'https://unsplash.com/@israelandrxde',
			'photos': 'https://api.unsplash.com/users/israelandrxde/photos',
			'likes': 'https://api.unsplash.com/users/israelandrxde/likes',
			'portfolio': 'https://api.unsplash.com/users/israelandrxde/portfolio',
			'following': 'https://api.unsplash.com/users/israelandrxde/following',
			'followers': 'https://api.unsplash.com/users/israelandrxde/followers',
		},
		'profile_image': {
			'small': 'https://images.unsplash.com/profile-fb-1522079523-fa0c89da8143.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
			'medium': 'https://images.unsplash.com/profile-fb-1522079523-fa0c89da8143.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
			'large': 'https://images.unsplash.com/profile-fb-1522079523-fa0c89da8143.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
		},
		'instagram_username': null,
		'total_collections': 0,
		'total_likes': 0,
		'total_photos': 5,
		'accepted_tos': true,
		'for_hire': false,
		'social': {
			'instagram_username': null,
			'portfolio_url': null,
			'twitter_username': null,
			'paypal_email': null,
		},
	},
	'tags': [
		{
			'type': 'search',
			'title': 'office',
		},
		{
			'type': 'landing_page',
			'title': 'company',
			'source': {
				'ancestry': {
					'type': {
						'slug': 'wallpapers',
						'pretty_slug': 'HD Wallpapers',
					},
					'category': {
						'slug': 'companies',
						'pretty_slug': 'Companies',
					},
				},
				'title': 'Hd company wallpapers',
				'subtitle': 'Download free company wallpapers',
				'description': 'Get right to business with Unsplash\'s collection of company wallpapers. Choose from a carefully curated selection of pristine HD images, all of them free.',
				'meta_title': 'Company Wallpapers: Free HD Download [500+ HQ] | Unsplash',
				'meta_description': 'Choose from hundreds of free company wallpapers. Download HD wallpapers for free on Unsplash.',
				'cover_photo': {
					'id': 'C2CYPENZ7LA',
					'slug': 'C2CYPENZ7LA',
					'created_at': '2017-10-24T13:01:48Z',
					'updated_at': '2023-06-13T18:02:13Z',
					'promoted_at': '2017-10-25T15:12:25Z',
					'width': 3120,
					'height': 1823,
					'color': '#262626',
					'blur_hash': 'LAA],K2k#@rYOWXA-WS#0w=#OqJ7',
					'description': 'Colourful noise',
					'alt_description': 'close view of busy city',
					'urls': {
						'raw': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?ixlib=rb-4.0.3',
						'full': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
						'regular': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
						'small': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
						'thumb': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max',
						'small_s3': 'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1508849789987-4e5333c12b78',
					},
					'links': {
						'self': 'https://api.unsplash.com/photos/C2CYPENZ7LA',
						'html': 'https://unsplash.com/photos/C2CYPENZ7LA',
						'download': 'https://unsplash.com/photos/C2CYPENZ7LA/download',
						'download_location': 'https://api.unsplash.com/photos/C2CYPENZ7LA/download',
					},
					'likes': 536,
					'liked_by_user': false,
					'current_user_collections': [],
					'sponsorship': null,
					'topic_submissions': {},
					'premium': false,
					'plus': false,
					'user': {
						'id': '8cLZBgAX2VU',
						'updated_at': '2023-06-10T16:36:46Z',
						'username': 'tjump',
						'name': 'Nik Shuliahin 💛💙',
						'first_name': 'Nik',
						'last_name': 'Shuliahin 💛💙',
						'twitter_username': null,
						'portfolio_url': 'https://www.behance.net/tjump',
						'bio': 'Christian + Filmmaker + Motion graphics designer\r\n If you are interested in collaborating, please contact me at nik.shuliahin [at] outlook.com',
						'location': 'Kyiv, Ukraine',
						'links': {
							'self': 'https://api.unsplash.com/users/tjump',
							'html': 'https://unsplash.com/@tjump',
							'photos': 'https://api.unsplash.com/users/tjump/photos',
							'likes': 'https://api.unsplash.com/users/tjump/likes',
							'portfolio': 'https://api.unsplash.com/users/tjump/portfolio',
							'following': 'https://api.unsplash.com/users/tjump/following',
							'followers': 'https://api.unsplash.com/users/tjump/followers',
						},
						'profile_image': {
							'small': 'https://images.unsplash.com/profile-1552699180569-836350fc2ddc?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
							'medium': 'https://images.unsplash.com/profile-1552699180569-836350fc2ddc?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
							'large': 'https://images.unsplash.com/profile-1552699180569-836350fc2ddc?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
						},
						'instagram_username': 'nik.shuliahin',
						'total_collections': 9,
						'total_likes': 1142,
						'total_photos': 85,
						'accepted_tos': true,
						'for_hire': true,
						'social': {
							'instagram_username': 'nik.shuliahin',
							'portfolio_url': 'https://www.behance.net/tjump',
							'twitter_username': null,
							'paypal_email': null,
						},
					},
				},
			},
		},
		{
			'type': 'search',
			'title': 'moderoffice',
		},
	],
},
];

const initialState: PhotoInterface.PhotoState = {
	listOfPhotos: [],
	loading: false,
	loadingLoadMore: false,
	total: 0,
	total_pages: 0,
	current_keyword: '',
	current_page: 1,
};

type Actions = { type: string; payload: any };

const contactReducers = (
	state = initialState,
	action: Actions,
): PhotoInterface.PhotoState => {
	const { type, payload } = action;
	console.log('type', type);
	switch (type) {
		case Dispatches.LOADING_PHOTO:
			return {
				...state,
				loading: payload,
			};
		case Dispatches.GET_PHOTO_BY_QUERY:
			return {
				...state,
				listOfPhotos: payload.results,
				total: payload.total,
				total_pages: payload.total_pages,
				current_keyword: payload.current_keyword,
				current_page: 1,
				loading: false,
			};
		case Dispatches.LOAD_MORE:
			return {
				...state,
				listOfPhotos: state.listOfPhotos.concat(payload.results),
				current_page: payload.page,
				loading: false,
			};
		default:
			return state;
	}
};

export default contactReducers;
